config/routes.rb
Rails.application.routes.draw do
  get 'matters/show'

  get 'messages/index'

  get 'messages/index'
  get 'posts/index'
  get 'matters/index'
  get 'stories/index'
  get 'problems/index' 
  get '/matters/index' => 'matters#index'
  get '/matters/:id' => 'matters#show', as: :matter
 

  root 'messages#index'
  
  resources :matters
  resources :posts do
    member do
      put "like", to: "links#upvote"
    end
  end
  resources :problems
  resources :messages

  
  
end

app/models/issue.rb
class Issue < ActiveRecord::Base
end

app/models/matter.rb
class Matter < ActiveRecord::Base
  has_many :posts
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :matters
  acts_as_votable
end

app/models/problem.rb
class Problem < ActiveRecord::Base
end

app/models/story.rb
class Story < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
  def index
    @new_matter = Matter.new
    @all_matters = Matter.order(created_at: :desc).all
  end

  def show 
    @matter = Matter.find(params[:id])
    @posts = @matter.posts
  end
  
  def create 
      @new_matter = Matter.new(post_params)
      if @new_matter.save
        redirect_to(:action => 'index')
      else 
        render new
      end
  end
  
  private
  def post_params
    params.require(:matter).permit(:content)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index 
    @messages = Message.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @new_post = Post.new
    @new_matter = Matter.new
    @all_posts = Post.order(created_at: :desc).all
    @all_matters = Matter.all
  end
  
  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user 
    redirect_to :back
  end 
  
  def create 
      @new_post = Post.new(post_params)
      if @new_post.save
        redirect_to(:action => 'index')
      else 
        render new
      end
      
      @new_matter = Matter.new(post_params)
      if @new_matter.save
        redirect_to(:action => 'index')
      else 
        render new
      end
  end
  
  private
  def post_params
    params.require(:post).permit(:story)
    params.require(:matter).permit(:content)
  end

 
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  def index
    @new_problem = Problem.new
    @all_problems = Problem.all
    @all_matters = Matter.all
  end
  
  def create 
      @new_problem = Problem.new(post_params)
      if @new_problem.save
        redirect_to(:action => 'index')
      else 
        render new
      end
  end
  
  private
  def post_params
    params.require(:problem).permit(:tag)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @new_post = Post.new
    @new_matter = Matter.new
    @all_posts = Post.order(created_at: :desc).all
    @all_matters = Matter.all
  end
  
  def create 
      @new_post = Post.new(post_params)
      if @new_post.save
        redirect_to(:action => 'index')
      else 
        render new
      end
      
      @new_matter = Matter.new(post_params)
      if @new_matter.save
        redirect_to(:action => 'index')
      else 
        render new
      end
  end
  
  private
  def post_params
    params.require(:post).permit(:story)
    params.require(:matter).permit(:content)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>peap</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/matters/index.html.erb
<div class="header">
   <div class="container">
     <h1>Submit a Matter</h1>
   </div>
</div>

<div class="main">
	<div class="container">
        
	   <%= form_for(@new_matter) do |f| %>
	             <%= f.text_field :content, :placeholder => "Share Your Thoughts" %>
	     <%= f.submit "Peap It", :class => "button.btn" %>
	   <% end %>

	   <ul class="contents">
	     <% @all_matters.each do |p| %>
	     <li> <%= p.content %> </li>
	     <% end %>
	   </ul>
	
	</div>
</div>
        

app/views/matters/show.html.erb
<!DOCTYPE html>
<html lang=“en”>
<head>
  <title>Peap</title>
  <link href='stylesheets/bootstrap.css' rel='stylesheet'>
  <script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <script src="javascripts/bootstrap.min.js"></script>
   <style>
    .menuhome1s1 {
      display: inline-block;
      position: absolute;
      left: 100px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-style: ridge;
      border-radius: 30px;
      margin-top: -70px;
      color: rgb(0, 143, 179);
    }
    .menuhome1s2 {
      display: inline-block;
      position: absolute;
      left: 290px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-style: ridge;
      border-radius: 30px;
      margin-top: -70px;
      color: rgb(0, 143, 179);
 
    }

    .menuhome2s1 {
      display: inline-block;
      position: absolute;
      right: 300px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-radius: 30px;
      border-style: ridge;
      margin-top: -70px;
      color: rgb(0, 143, 179);
    }
    
    .menuhome2s2 {
      display: inline-block;
      position: absolute;
      right: 100px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-radius: 30px;
      border-style: ridge;
      margin-top: -70px;
      color: rgb(0, 143, 179);
    }

    #stories1 {   
      text-align: center;
      background-color: rgb(255, 255, 255);
    }

    .storie {
      margin-top: 20px;
      position: relative;
      background-color: rgba(0, 143, 179, 0.6);
      width: 700px;
      text-align: center;
    }

    .try {
      border-color: rgb(255, 255, 0);
      border-width: 5px;
      border-style: dashed;
      width: 700px;
      height: 200px;
      margin-left: 100px;
      margin-top: 20px;
   

    }
   </style>
</head> 

<body>
  <div class="jumbotron" id="stories1" >
    <a href="/problems/index">
        <div class="menuhome1s1">
          <br> DISCOVER <br> A <br> PEAP
        </div>
      </a>
      <a href="/posts">
        <div class="menuhome1s2">
          <br> PROFESS <br> A <br> PEAP
        </div>
      </a>
      <a href="/stories/index">
        <div class="menuhome2s1">
          <br> ALL <br> <br> PEAPS
        </div>
      </a>
      <a href="">
        <div class="menuhome2s2">
          <br> ABOUT <br> <br> PEAP
        </div>
      </a>
      <h1 class="text-center">PEAP</h1>
  <!--  <div class=box1>
      <p>You Inspire Me</p>
    </div>
    <div class=box2>
      <p>Bravo!</p>
    </div>
    <div class=box3>
      <p>Can relate!</p>
    </div>
    <div class=box4>
      <p>Share</p>
    </div> -->

      <div class="try"></div>

      <div class="stories">
       <% @posts.each do |post| %>
       <div class="storie"> <%= post.story %> </div>
       <% end %>
     </div> 
	 
   
	    <div class="boxxx"></div>
  <!--  <div class=option1>
      <img src="/assets/circle.png" class="img-responsive" id='circ' alt="star">
    </div>
    <div class=option11>
      <img src="/assets/smiley.png" class="img-responsive" id='smil' alt="star">
    </div>
    <div class=option2>
      <img src="/assets/blank.png" class="img-responsive" id='blank' alt="star">
    </div>
    <div class=option21>
      <img src="/assets/star.png" class="img-responsive" id='star' alt="star">
    </div>
    <div class=option3>
    </div>  -->
 </div>
 <script>
  var main = function() {

 // document.getElementById('boxxx').innerHTML = vall();
  
  
  $('.box1').click(function() {
    $(this).addClass('clicked');
    var circ = document.getElementById('circ');
    circ.parentNode.removeChild(circ);

    document.getElementById('smil').style.visibility = "visible"
        
  });

  $('.box2').click(function() {
    $(this).addClass('clicked2');
    var blank = document.getElementById('blank');
    blank.parentNode.removeChild(blank);

    document.getElementById('star').style.visibility = "visible"
        
  });

  $('.box3').click(function() {
    $(this).addClass('clicked3');
  });
    

};

$(document).ready(main);
 </script>
</body>
</html>

app/views/messages/index.html.erb
<html>
<head>
  <title>Peap</title>
  <link href='stylesheets/bootstrap.css' rel='stylesheet'>
  <script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <script src="javascripts/bootstrap.min.js"></script>
  <script>
     var main = function() {
        $('.co').animate({cy: '0px', y:'0px'}, 
          5000, function(){
            $('.c1').animate({cx: '350px', cy:'100px;'}, 900);
            $('.c2').animate({cx: '550px', cy:'100px;'}, 900);
          /*  $('.c3').animate({cx: '260px'}, 900);
            $('.c4').animate({cx: '640px'}, 900);  */

            $('.c1').fadeTo("slow", 0.6);
            $('.c2').fadeTo("slow", 0.6);

            $('.he').css("opacity", 1);  

        });
     };

     $(document).ready(main);
  </script>
  <style>

    .jumbotron {
      height: 700px;
      
      color: rgb(0, 143, 179);
      background-color: rgb(255, 255, 255);
    }

    .explain {
      height: 700px;
      position: relative;
      background-color: rgb(0, 255, 255);
      margin-top: -120px;
    }
    .pea {
      margin-top: 150px;
    }
    .circleh {
    margin-left: 150px;
    width: 100px;
    height: 100px;
    -moz-border-radius: 50px;
    -webkit-border-radius: 50px;
    border-radius: 50px;
    border-color: #000000;
    color: transparent;
    } 

    .he {
      opacity: 0.1;
      color: #003B46;
    }


    .svg-container2 {
      display: inline-block;
      
      width: 800px;
      height: 500px;
     
    }

    .svg-content {
      position: absolute;
      top: 280px;
      left: 0px;
    }
  
    
    .menuhome1m1 {
      display: inline-block;
      position: absolute;
      left: 100px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-style: ridge;
      border-radius: 30px;
      margin-top: -70px;
      color: rgb(0, 143, 179);
     
    }

    .menuhome1m2 {
      display: inline-block;
      position: absolute;
      left: 290px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-style: ridge;
      border-radius: 30px;
      margin-top: -70px;
      color: rgb(0, 143, 179);
     
    }


    
    .menuhome2m1 {
      display: inline-block;
      position: absolute;
      right: 300px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-radius: 30px;
      border-style: ridge;
      margin-top: -60px;
      color: rgb(0, 143, 179);
    }
    
    .menuhome2m2 {
      display: inline-block;
      position: absolute;
      right: 100px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-radius: 30px;
      border-style: ridge;
      margin-top: -60px;
      color: rgb(0, 143, 179);
    }
  


   
  </style>
</head>
<body>
  <div class="jumbotron">
      <a href="/problems/index">
        <div class="menuhome1m1">
          <br> DISCOVER <br> A <br> PEAP
        </div>
      </a>
      <a href="/posts">
        <div class="menuhome1m2">
          <br> PROFESS <br> A <br> PEAP
        </div>
      </a>
      <a href="/stories/index">
        <div class="menuhome2m1">
          <br> ALL <br> <br> PEAPS
        </div>
      </a>
      <a href="">
        <div class="menuhome2m2">
          <br> ABOUT <br> <br> PEAP
        </div>
      </a>
    
    <h1 class="text-center">PEAP</h1>
    <p class="text-center">Find peace in pain</p>
    <p class="he text-center">OR Help others find peace in pain</p>
     
    <div class="svg-container2">
     <svg viewBox="10 0 900 900" preserveAspectRatio="xMinYMin meet" class="svg-content">
    <!--  <path d='M 25,60 
           a 20,20 1 0,0 0,40 
           h 50 
           a 20,20 1 0,0 0,-40 
           a 10,10 1 0,0 -15,-10 
           a 15,15 1 0,0 -35,10  
           z' style="fill:yellow; margin-left:30px; margin-top:-100px;"/> 
      <a <strong>xlink:href="http://example.com/link/"</strong>>
         <text x="10" y="25" >An example link.</text>
      </a> -->
      <circle cx="380" cy="130" r="90" fill="rgba(0, 96, 128, 0.7)
" class="c1"/>
      <circle cx="520" cy="130" r="90" fill="rgb(0, 143, 179)" class="c2" />
     <!-- <circle cx="600" cy="175" r="150" fill="#FF420E" class="c2" /> 
  rgb(102, 0, 0)   rgb(0, 128, 0)   rgb(255, 255, 51)
      <circle cx="450" cy="240" r="140" fill="#80BD9E" class="c3"/> 
      <circle cx="750" cy="250" r="140" fill="rgb(76, 181, 245)" class="c4" />  -->
      


      <circle cx="100" cy="250" r="50" class="co" id="co" fill="rgb(255, 255, 0)" />
      <text x="85" y="25" style="font-size:10px;">PEAP</text>
    

      <circle cx="450" cy="190" r="15" style="fill:yellow;"/>
      <text x="440" y="195" style="font-size:10px;">MAN</text>
      <text x="340" y="135" style="font-size:10px; fill:rgb(0, 143, 179)">PAIN</text>
      <text x="540" y="135" style="font-size:10px; fill:rgba(0, 96, 128, 0.7);">PAIN</text>


   <!--   <path d="M 50 100 L 62 110 68 97 " fill="yellow" />
      <path d="M 80 90 L 92 100 98 87 " fill="yellow" />
      <path d="M 110 100 L 62 110 68 97 " fill="yellow" />
      <path d="M 50 100 L 62 110 68 97 " fill="yellow" /> -->


     <!-- <line x1="450" y1="220" x2="450" y2="180" style="stroke:rgb(255,0,0);stroke-width:5" />

      <line x1="450" y1="210" x2="450" y2="230" style="stroke:rgb(255,0,0);stroke-width:5" />
      <line x1="450" y1="210" x2="490" y2="230" style="stroke:rgb(255,0,0);stroke-width:5" /> 
      
      <line x1="450" y1="250" x2="420" y2="270" style="stroke:rgb(255,0,0);stroke-width:5" /> 
      <line x1="450" y1="250" x2="460" y2="270" style="stroke:rgb(255,0,0);stroke-width:5" />  -->

     <!-- <rect y="270" width="100%" height="150" style="fill:#ffffff;" /> -->

      
     </svg>
    </div>

  </div>   



</body>
</body>
</html>

app/views/posts/index.html.erb
<html>
<head>
  <title>Peap</title>
  <link href='stylesheets/bootstrap.css' rel='stylesheet'>
  <script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <script src="javascripts/bootstrap.min.js"></script>
   <style>
   #posts1 {
   	  background-color: rgb(255, 255, 255);
   	  height: 800px;
   	  text-align: center;
   	  color: rgb(0, 143, 179);

   }

   .material {
      margin-left: 200px;
      margin-right: 200px;
      text-align: center;
  }

   .storc {
      display: block;
      border-color: rgb(0, 143, 179);;
      border-width: 5px;
      border-style: double dashed;
      margin-top: 10px;
      height: 500px;

      width: 100%;
   
     

    /* margin-top: 20px;
   	 width: 700px;
   	 height: 500px;
   	 border-radius: 20px;
   	 border-style: ridge;
   	 border-color: rgb(255, 255, 0);
   	 text-align: center;
   	 background-color:  rgba(0, 143, 179, 0.2); */
   }

   .storctit {
     display: block;
     width: 100%;
     border-color: rgb(0, 143, 179);;
     border-width: 1px;
     border-style: ridge;
    
   }
   .storcmat {
    display: block;
    height: 40px;
    
   

   }
   .storcbut {
   	 position: relative;
   	 display: block;
     width: 100%;
     

   	
   }


   .storc1 {
   	 position: relative;
   	 top: 150px;
   	 
   }

  .menuhome1po1 {
      display: inline-block;
      position: absolute;
      left: 100px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-style: ridge;
      border-radius: 30px;
      margin-top: -70px;
      color: rgb(0, 143, 179);
     
    }

    .menuhome1po2 {
      display: inline-block;
      position: absolute;
      left: 290px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-style: ridge;
      border-radius: 30px;
      margin-top: -70px;
      color: rgb(0, 143, 179);
     
    }

    .menuhome2po1 {
      display: inline-block;
      position: absolute;
      right: 300px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-radius: 30px;
      border-style: ridge;
      margin-top: -70px;
      color: rgb(0, 143, 179);
    }
    
    .menuhome2po2 {
      display: inline-block;
      position: absolute;
      right: 100px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-radius: 30px;
      border-style: ridge;
      margin-top: -70px;
      color: rgb(0, 143, 179);
    }
  

    .contents {
        text-align: center;
    }
    
    
    .content {
    	margin-top: 20px;
    	position: relative;
    	background-color: rgba(0, 143, 179, 0.6);
    	width: 700px;
    	text-align: center;

    }

    .voting {
  
      text-align: center;
    }
   </style>
</head>
<body>
  <div class="jumbotron" id="posts1">
     <a href="/problems/index">
        <div class="menuhome1po1">
          <br> DISCOVER <br> A <br> PEAP
        </div>
      </a>
      <a href="/posts">
        <div class="menuhome1po2">
          <br> PROFESS <br> A <br> PEAP
        </div>
      </a>
      <a href="/stories/index">
        <div class="menuhome2po1">
          <br> ALL <br> <br> PEAPS
        </div>
      </a>
      <a href="">
        <div class="menuhome2po2">
          <br> ABOUT <br> <br> PEAP
        </div>
      </a>
    <h1 class="text-center">PEAP</h1>
    <p class="text-center">Peace in Pain</p>
 
    <div class="material">
     
	   <%= form_for(@new_post) do |f| %> 
               <br><br>
               Title : <%= f.text_field :title, class: 'storctit' %> <br>
	            <%= f.text_area :story, :cols => 40, :rows => 15, class: 'storc', :placeholder => "Share Your Thoughts
	            																	Peep into your life" %> <br><br>
              Matter : <%= f.collection_select( :matter_id, Matter.all, :id, :content) %> <br><br>
	            <%= f.submit "Peap It", :class => "button.btn", class: 'storcbut' %>
	   <% end %>
    </div>

	   
    <!--   <%= form_for(@new_matter) do |f| %>
             <%= f.text_field :content, class: 'storc1', :placeholder => "Share Your Thoughts" %>

       <%= f.submit "Peap It", :class => "button.btn" %>
       <% end %> -->

     <!--  <div class="contents">
          <% @all_matters.each do |p| %>
              <div class="content"> <%= p.content %> </div>
          <% end %>
       </div> -->
	   
       <div class="voting">
         <% @all_posts.each do |post| %>
         <h4><%= link_to post.title, post %><br>
          Submitted <%= time_ago_in_words(post.created_at) %> 
         </h4>
         <%= link_to like_link_path(post), method: :put do %>
         Upvote
         <%= post.get_upvotes.size %>
         <% end %>
         <% end %>
       </div>
	   
	<!-- <div class="controls">
       <%= collection_select( :matter, :matter_id, Matter.all, :content, :content) %>
     </div> -->
  </div>
</body>
</html>
        

app/views/stories/index.html.erb
<!DOCTYPE html>
<html lang=“en”>
<head>
  <title>Peap</title>
  <link href='stylesheets/bootstrap.css' rel='stylesheet'>
  <script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <script src="javascripts/bootstrap.min.js"></script>
   <style>
    .menuhome1s1 {
      display: inline-block;
      position: absolute;
      left: 100px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-style: ridge;
      border-radius: 30px;
      margin-top: -70px;
      color: rgb(0, 143, 179);
    }
    .menuhome1s2 {
      display: inline-block;
      position: absolute;
      left: 290px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-style: ridge;
      border-radius: 30px;
      margin-top: -70px;
      color: rgb(0, 143, 179);
 
    }

    .menuhome2s1 {
      display: inline-block;
      position: absolute;
      right: 300px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-radius: 30px;
      border-style: ridge;
      margin-top: -70px;
      color: rgb(0, 143, 179);
    }
    
    .menuhome2s2 {
      display: inline-block;
      position: absolute;
      right: 100px;
      width: 90px;
      height: 90px;
      text-align: center;
      border-width: 1px;
      border-color: rgb(255, 255, 0);
      border-radius: 30px;
      border-style: ridge;
      margin-top: -70px;
      color: rgb(0, 143, 179);
    }

    #stories1 {   
      text-align: center;
      background-color: rgb(255, 255, 255);
      color: rgb(0, 143, 179);
    }

    .storie {
      border-color: rgb(0, 143, 179);;
      border-width: 5px;
      border-style: double dashed;
      margin-left: 180px;
      margin-right: 220px;
      margin-top: 50px;
    }

    .try {
      border-color: rgb(0, 143, 179);;
      border-width: 5px;
      border-style: double dashed;
      margin-left: 180px;
      margin-right: 220px;
      margin-top: 50px;
      height: 500px;
    }

   </style>
</head> 

<body>
  <div class="jumbotron" id="stories1" >
    <a href="/problems/index">
        <div class="menuhome1s1">
          <br> DISCOVER <br> A <br> PEAP
        </div>
      </a>
      <a href="/posts">
        <div class="menuhome1s2">
          <br> PROFESS <br> A <br> PEAP
        </div>
      </a>
      <a href="/stories/index">
        <div class="menuhome2s1">
          <br> ALL <br> <br> PEAPS
        </div>
      </a>
      <a href="">
        <div class="menuhome2s2">
          <br> ABOUT <br> <br> PEAP
        </div>
      </a>
      <h1 class="text-center">PEAP</h1>
  <!--  <div class=box1>
      <p>You Inspire Me</p>
    </div>
    <div class=box2>
      <p>Bravo!</p>
    </div>
    <div class=box3>
      <p>Can relate!</p>
    </div>
    <div class=box4>
      <p>Share</p>
    </div> -->

      <div class="try"></div> 

      <div class="stories">
       <% @all_posts.each do |p| %>
       <div class="storie"> <%= p.story %> </div>
       <% end %>
     </div> 
	 
   
	    <div class="boxxx"></div>
  <!--  <div class=option1>
      <img src="/assets/circle.png" class="img-responsive" id='circ' alt="star">
    </div>
    <div class=option11>
      <img src="/assets/smiley.png" class="img-responsive" id='smil' alt="star">
    </div>
    <div class=option2>
      <img src="/assets/blank.png" class="img-responsive" id='blank' alt="star">
    </div>
    <div class=option21>
      <img src="/assets/star.png" class="img-responsive" id='star' alt="star">
    </div>
    <div class=option3>
    </div>  -->
 </div>
 <script>
  var main = function() {

 // document.getElementById('boxxx').innerHTML = vall();
  
  
  $('.box1').click(function() {
    $(this).addClass('clicked');
    var circ = document.getElementById('circ');
    circ.parentNode.removeChild(circ);

    document.getElementById('smil').style.visibility = "visible"
        
  });

  $('.box2').click(function() {
    $(this).addClass('clicked2');
    var blank = document.getElementById('blank');
    blank.parentNode.removeChild(blank);

    document.getElementById('star').style.visibility = "visible"
        
  });

  $('.box3').click(function() {
    $(this).addClass('clicked3');
  });
    

};

$(document).ready(main);
 </script>
</body>
</html>